### PR TITLE
docs(fireblocks-signing-manager): improve README readability

### PR DESCRIPTION
**Pull request by polymath-eric**
### Description

add some additional information and remove some redundant words for the README

### Checklist

- [X] Updated the Readme.md (if required) ?

### CODE REVIEW

**Comment by polymath-eric** [comment]
Some small edits I noticed when looking at the npm page to make sure that got published properly.

**Review by VictorVicente — APPROVED** [review]

**Review by prashantasdeveloper — APPROVED** [review]

**Pull request merged**
